"""Add unix timestamp expiration to login links

Revision ID: 0bf5e233f2fd
Revises: 1ede389cf74f
Create Date: 2020-10-02 01:42:04.199168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bf5e233f2fd'
down_revision = '1ede389cf74f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loginlink', sa.Column('expires_at_timestamp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loginlink', 'expires_at_timestamp')
    # ### end Alembic commands ###
