"""add invites

Revision ID: 527df90c64df
Revises: 1463b2ce7c95
Create Date: 2020-10-03 17:34:15.002462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '527df90c64df'
down_revision = '1463b2ce7c95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('NO_RESPONSE', 'NO', 'MAYBE', 'YES', name='invitestatus'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invite_event_id'), 'invite', ['event_id'], unique=False)
    op.create_index(op.f('ix_invite_id'), 'invite', ['id'], unique=False)
    op.create_index(op.f('ix_invite_user_id'), 'invite', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invite_user_id'), table_name='invite')
    op.drop_index(op.f('ix_invite_id'), table_name='invite')
    op.drop_index(op.f('ix_invite_event_id'), table_name='invite')
    op.drop_table('invite')
    # ### end Alembic commands ###
