"""Remove userevent association

Revision ID: 93e37d267cfc
Revises: 527df90c64df
Create Date: 2020-10-03 17:47:48.481976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93e37d267cfc'
down_revision = '527df90c64df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_event')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_event',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name='user_event_event_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_event_user_id_fkey')
    )
    # ### end Alembic commands ###
