"""Added unique codes to invites

Revision ID: 9b03d09db34f
Revises: de7a914273f6
Create Date: 2020-10-04 21:28:18.697536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b03d09db34f'
down_revision = 'de7a914273f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite', sa.Column('code', sa.String(), nullable=True))
    op.create_index(op.f('ix_invite_code'), 'invite', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invite_code'), table_name='invite')
    op.drop_column('invite', 'code')
    # ### end Alembic commands ###
