"""Add phone number to user

Revision ID: d00dd7d72d43
Revises: 0bf5e233f2fd
Create Date: 2020-10-02 22:45:28.967238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd00dd7d72d43'
down_revision = '0bf5e233f2fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('number', sa.String(length=11), nullable=True))
    op.create_index(op.f('ix_user_number'), 'user', ['number'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_number'), table_name='user')
    op.drop_column('user', 'number')
    # ### end Alembic commands ###
