"""Add login link table

Revision ID: ee552bd361f7
Revises: f19151e0aec0
Create Date: 2020-09-22 22:08:45.631191

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ee552bd361f7"
down_revision = "f19151e0aec0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "login_link",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=True, default=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_login_link_code"), "login_link", ["code"], unique=True)
    op.create_index(op.f("ix_login_link_id"), "login_link", ["id"], unique=False)
    op.create_index(
        op.f("ix_login_link_user_id"), "login_link", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_login_link_user_id"), table_name="login_link")
    op.drop_index(op.f("ix_login_link_id"), table_name="login_link")
    op.drop_index(op.f("ix_login_link_code"), table_name="login_link")
    op.drop_table("login_link")
    # ### end Alembic commands ###
