"""Add date to event

Revision ID: f19151e0aec0
Revises: f60ebc211489
Create Date: 2020-09-20 17:50:09.133779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f19151e0aec0'
down_revision = 'f60ebc211489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'date')
    # ### end Alembic commands ###
